spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

# 阿里巴巴druid数据源配置 
druid:
  default-auto-commit: false
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/movie_8001?unicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: admin
  initial-size: 1
  min-idle: 1
  max-active: 20
  max-wait: 60000
  min-evictable-idle-time-millis: 300000
  pool-prepared-statements: true
  time-between-eviction-runs-millis: 60000
  max-pool-prepared-statement-per-connection-size: 20
  
# mybatis配置文件、mapper文件、entity包位置
mybatis:
  config-location: mybatis-config.xml
  mapper-locations: mapper/**.xml
  type-aliases-package: com.zhihao.movie.api.entity
  
# thymeleaf模板视图
spring:
  thymeleaf:
    cache: false
    template-resolver-order: 0
    prefix: classpath:/templates/
    suffix: .html
  profiles: dev
  application:
    name: movie-config-provider-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: movie8001.com      # 在eureka server中显示的实例名称
    prefer-ip-address: true               # 显示id
    
info:
  app.name: movie-config01
  company.name: com.zhihao
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

# 阿里巴巴druid数据源配置 
druid:
  default-auto-commit: false
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/movie_8002?unicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: admin
  initial-size: 1
  min-idle: 1
  max-active: 20
  max-wait: 60000
  min-evictable-idle-time-millis: 300000
  pool-prepared-statements: true
  time-between-eviction-runs-millis: 60000
  max-pool-prepared-statement-per-connection-size: 20
  
# mybatis配置文件、mapper文件、entity包位置
mybatis:
  config-location: mybatis-config.xml
  mapper-locations: mapper/**.xml
  type-aliases-package: com.zhihao.movie.api.entity
  
# thymeleaf模板视图
spring:
  thymeleaf:
    cache: false
    template-resolver-order: 0
    prefix: classpath:/templates/
    suffix: .html
  profiles: test
  application:
    name: movie-config-provider-client
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: movie8001.com      # 在eureka server中显示的实例名称
    prefer-ip-address: true               # 显示id
    
info:
  app.name: movie-config02
  company.name: com.zhihao
  build.artifactId: $project.artifactId$
  build.version: $project.version$